pipeline {
    agent any

    //     environment {
    //         JAVA_HOME = '/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-4.el8_5.x86_64'
    //         MAVEN_HOME = '/usr/share/maven'
    //     }

    stages {
        stage('Info') {
            steps {
                echo 'Print thee system environment...'
                sh 'printenv'
            }
        }

        stage ('Clone') {
            steps {
                echo 'Clone the application source...'
                git branch: 'maven-dev', url: "https://github.com/selvasabapathy/project-examples.git"
            }
        }

        stage ('Config') {
            steps {
                echo 'Configure artifactory deployer and resolver...'
                //                 rtServer (
                //                     id: "ARTIFACTORY_SERVER",
                //                     url: 'http://10.176.0.212',
                //                     credentialsId: 'artifactoryCredentials'
                //                 )
                rtMavenDeployer (
                    id: 'MAVEN_DEPLOYER',
                    serverId: 'ARTIFACTORY_SERVER',
                    releaseRepo: 'pe-maven-virtual',
                    snapshotRepo: 'pe-maven-virtual',
                    properties: ['deployerName=Selva', 'deployerLocation=Atlanta']
                )
                rtMavenResolver (
                    id: 'MAVEN_RESOLVER',
                    serverId: 'ARTIFACTORY_SERVER',
                    releaseRepo: 'pe-maven-virtual',
                    snapshotRepo: 'pe-maven-virtual'
                )
            }
        }

        stage ('Build') {
            steps {
                echo 'Build the application...'
                rtMavenRun (
                    tool: 'MAVEN-3.5.4',
                    pom: 'maven-examples/maven-example/pom.xml',
                    goals: 'clean install',
                    deployerId: 'MAVEN_DEPLOYER',
                    resolverId: 'MAVEN_RESOLVER'
                )
            }
        }

        stage ('Build info') {
            steps {
                echo 'Push build info to artifactory...'
                rtPublishBuildInfo (
                    serverId: "ARTIFACTORY_SERVER"
                )
            }
        }
    }
}
