pipeline {
    agent any

    //     environment {
    //         JAVA_HOME = '/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-4.el8_5.x86_64'
    //         MAVEN_HOME = '/usr/share/maven'
    //     }

    stages {
        stage('Info') {
            steps {
                echo 'Print thee system environment...'
                sh 'printenv'
            }
        }

        stage('JFrog CLI Info') {
            steps {
                echo 'Print thee JFrog CLI environment...'
                sh 'jf c s'
            }
        }

        stage ('Clone') {
            steps {
                echo 'Clone the application source...'
                git branch: 'maven-cli-dev', url: "https://github.com/selvasabapathy/project-examples.git"
            }
        }

        stage ('Build') {
            steps {
                echo 'Build the application...'
                sh 'jf mvn -f maven-examples/maven-example/pom.xml clean install'
            }
        }

        stage ('Build info') {
            steps {
                echo 'Push build info to artifactory...'
                sh 'jf rt bp'
            }
        }

        stage ('Scan') {
            steps {
                echo 'Scan for security & license...'
                sh 'jf xr am --fail false'
            }
        }
    }
}
